import mods.avaritia.ExtremeCrafting;
import mods.jei.JEI;

//Black Panther's Necklace
recipes.remove(<wakanda:black_panther_infinity_suit>);
ExtremeCrafting.addShaped("insanecraft_infinity_necklace", <wakanda:black_panther_infinity_suit>, [
[null, null, null, null, null, null, null, null, null], 
[null, null, null, null, null, null, null, null, null],
[null, null, <lucraftcore:ingot_gold_titanium_alloy>, <lucraftcore:ingot_gold_titanium_alloy>, <lucraftcore:ingot_gold_titanium_alloy>, <lucraftcore:ingot_gold_titanium_alloy>, <lucraftcore:ingot_gold_titanium_alloy>, null, null],
[null, <lucraftcore:ingot_gold_titanium_alloy>, <infinity:mind_stone>, <taiga:vibranium_ingot>, <infinity:power_stone>, <taiga:vibranium_ingot>, <infinity:reality_stone>, <lucraftcore:ingot_gold_titanium_alloy>, null],
[<lucraftcore:ingot_gold_titanium_alloy>, <avaritia:resource:5>, <taiga:vibranium_ingot>, <singularities:singularity:26>, <heroesexpansion:black_panther_suit>, <singularities:singularity:26>, <taiga:vibranium_ingot>, <avaritia:resource:5>, <lucraftcore:ingot_gold_titanium_alloy>],
[null, <lucraftcore:ingot_gold_titanium_alloy>, <infinity:space_stone>, <taiga:vibranium_ingot>, <avaritia:resource:5>, <taiga:vibranium_ingot>, <infinity:soul_stone>, <lucraftcore:ingot_gold_titanium_alloy>, null],
[null, null, <lucraftcore:ingot_gold_titanium_alloy>, <lucraftcore:ingot_gold_titanium_alloy>, <infinity:time_stone>, <lucraftcore:ingot_gold_titanium_alloy>, <lucraftcore:ingot_gold_titanium_alloy>, null, null],
[null, null, null, null, <lucraftcore:ingot_gold_titanium_alloy>, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Sword of the Cosmos
ExtremeCrafting.remove(<avaritia:infinity_sword>);
mods.avaritia.ExtremeCrafting.addShaped("CosmoSword", <avaritia:infinity_sword> * 1, [[null, null, null, null, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>], [null, null, null, null, null, null, <avaritia:resource:6>, <avaritia:block_resource:1>, <avaritia:resource:6>],[null, null, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, null],[null, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, null, null],[null, <avaritia:resource:1>, null, <avaritia:resource:6>, <avaritia:block_resource:1>, <avaritia:resource:6>, null, null, null],[null, null, <avaritia:resource:1>, <avaritia:resource:6>, <avaritia:resource:6>, null, null, null, null],[null, null, <avaritia:resource:4>, <avaritia:resource:1>, null, null, null, null, null],[null, <avaritia:resource:4>, null, null, <avaritia:resource:1>, null, null, null, null],[<avaritia:resource:5>, null, null, null, null, null, null, null, null]]);

//Lost Infinity Book
recipes.addShaped("sanemake_infinitylostbook", <patchouli:guide_book>.withTag({"patchouli:book": "patchouli:lostinfinity"}), [
[null, <minecraft:book>, null], 
[null, <lostinfinity:celestialminerspickaxe>, null],
[null, null, null]]);

// Creative CAD Assembly
mods.avaritia.ExtremeCrafting.remove(<psi:cad_assembly:5>);
mods.avaritia.ExtremeCrafting.addShaped("creatvecad", <psi:cad_assembly:5> * 1, [[<avaritia:endest_pearl>, <singularities:singularity:3>, <singularities:singularity:3>, <singularities:singularity:3>, <avaritia:resource:6>, <singularities:singularity:3>, <singularities:singularity:3>, <singularities:singularity:3>, <avaritia:endest_pearl>], [<singularities:singularity:3>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <singularities:singularity:3>],[<singularities:singularity:3>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, <singularities:singularity:3>],[<singularities:singularity:3>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:block_resource:1>, <psi:psi_decorative:2>, <avaritia:block_resource:1>, <avaritia:resource:6>, <avaritia:resource:4>, <singularities:singularity:3>],[<avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <psi:psi_decorative:2>, <psi:cad_assembly:4>, <psi:psi_decorative:2>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>],[<singularities:singularity:3>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:block_resource:1>, <psi:psi_decorative:2>, <avaritia:block_resource:1>, <avaritia:resource:6>, <avaritia:resource:4>, <singularities:singularity:3>],[<singularities:singularity:3>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>, <singularities:singularity:3>],[<singularities:singularity:3>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <singularities:singularity:3>],[<avaritia:endest_pearl>, <singularities:singularity:3>, <singularities:singularity:3>, <singularities:singularity:3>, <avaritia:resource:6>, <singularities:singularity:3>, <singularities:singularity:3>, <singularities:singularity:3>, <avaritia:endest_pearl>]]);

// Flux Capacitor (Creative)
mods.avaritia.ExtremeCrafting.remove(<thermalexpansion:capacitor:32000>);
mods.avaritia.ExtremeCrafting.addShaped("creatvecap", <thermalexpansion:capacitor:32000> * 1, [[<avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <singularities:singularity:3>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>], [<avaritia:resource:6>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <singularities:singularity:3>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <avaritia:resource:6>],[<avaritia:resource:6>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <singularities:singularity:3>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <avaritia:resource:6>],[<avaritia:resource:6>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <singularities:singularity:10>, <singularities:singularity:3>, <singularities:singularity:10>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <avaritia:resource:6>],[<singularities:singularity:3>, <singularities:singularity:3>, <singularities:singularity:3>, <singularities:singularity:3>, <thermalexpansion:capacitor:4>, <singularities:singularity:3>, <singularities:singularity:3>, <singularities:singularity:3>, <singularities:singularity:3>],[<avaritia:resource:6>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <singularities:singularity:10>, <singularities:singularity:3>, <singularities:singularity:10>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <avaritia:resource:6>],[<avaritia:resource:6>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <singularities:singularity:3>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <avaritia:resource:6>],[<avaritia:resource:6>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <singularities:singularity:3>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <thermalexpansion:dynamo:4>, <avaritia:resource:6>],[<avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <singularities:singularity:3>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>]]);

//  Neutronium Solar Panel - temp disabled till oregen is controllable.
mods.avaritia.ExtremeCrafting.remove(<mekanismecoenergistics:avaritiagenerator:1>);
mods.avaritia.ExtremeCrafting.addShaped("nutroniumsolar", <mekanismecoenergistics:avaritiagenerator:1> * 1, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null],[null, null, <mekanismecoenergistics:solarcellavaritia:1>, <mekanismecoenergistics:solarcellavaritia:1>, <mekanismecoenergistics:solarcellavaritia:1>, <mekanismecoenergistics:solarcellavaritia:1>, <mekanismecoenergistics:solarcellavaritia:1>, null, null],[null, null, <mekanismecoenergistics:compressedavaritia:1>, <mekanismecoenergistics:controlcircuitavaritia:1>, <mekanismecoenergistics:avaritiagenerator:0>, <mekanismecoenergistics:controlcircuitavaritia:1>, <mekanismecoenergistics:compressedavaritia:1>, null, null],[null, null, <mekanismecoenergistics:compressedavaritia:1>, <mekanismecoenergistics:alloyavaritia:1>, <mekanismecoenergistics:compressedavaritia:1>, <mekanismecoenergistics:alloyavaritia:1>, <mekanismecoenergistics:compressedavaritia:1>, null, null],[null, null, <mekanismecoenergistics:compressedavaritia:1>, <singularities:singularity:3>, <mekanismecoenergistics:compressedavaritia:1>, <singularities:singularity:2>, <mekanismecoenergistics:compressedavaritia:1>, null, null],[null, null, <mekanismecoenergistics:compressedavaritia:1>, <mekanismecoenergistics:compressedavaritia:1>, <mekanismecoenergistics:compressedavaritia:1>, <mekanismecoenergistics:compressedavaritia:1>, <mekanismecoenergistics:compressedavaritia:1>, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

//  Solar Panel of Infinity - temp disabled till oregen is controllable.
mods.avaritia.ExtremeCrafting.remove(<mekanismecoenergistics:avaritiagenerator:2>);
mods.avaritia.ExtremeCrafting.addShaped("infinipanel", <mekanismecoenergistics:avaritiagenerator:2> * 1, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null],[null, null, <mekanismecoenergistics:solarcellavaritia:2>, <mekanismecoenergistics:solarcellavaritia:2>, <mekanismecoenergistics:solarcellavaritia:2>, <mekanismecoenergistics:solarcellavaritia:2>, <mekanismecoenergistics:solarcellavaritia:2>, null, null],[null, null, <avaritia:resource:5>, <mekanismecoenergistics:controlcircuitavaritia:2>, <mekanismecoenergistics:avaritiagenerator:1>, <mekanismecoenergistics:controlcircuitavaritia:2>, <avaritia:resource:5>, null, null],[null, null, <avaritia:resource:5>, <mekanismecoenergistics:alloyavaritia:2>, <mekanismecoenergistics:compressedavaritia:2>, <mekanismecoenergistics:alloyavaritia:2>, <avaritia:resource:5>, null, null],[null, null, <avaritia:resource:5>, <singularities:singularity:10>, <mekanismecoenergistics:compressedavaritia:1>, <singularities:singularity:10>, <avaritia:resource:5>, null, null],[null, null, <mekanismecoenergistics:compressedavaritia:2>, <mekanismecoenergistics:compressedavaritia:1>, <mekanismecoenergistics:compressedavaritia:1>, <mekanismecoenergistics:compressedavaritia:1>, <mekanismecoenergistics:compressedavaritia:2>, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Turbine Creative Steam Generator (Legacy)
mods.avaritia.ExtremeCrafting.remove(<bigreactors:turbinecreativesteamgenerator>);
mods.avaritia.ExtremeCrafting.addShaped("creatvesteamgen", <bigreactors:turbinecreativesteamgenerator> * 1, [[<singularities:singularity:1>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <singularities:singularity:1>], [<avaritia:resource:4>, <bigreactors:oreanglesite>, <bigreactors:oreanglesite>, <bigreactors:oreanglesite>, <avaritia:resource:6>, <bigreactors:oreanglesite>, <bigreactors:oreanglesite>, <bigreactors:oreanglesite>, <avaritia:resource:4>],[<avaritia:resource:4>, <bigreactors:oreanglesite>, <bigreactors:blockludicrite>, <bigreactors:blockludicrite>, <bigreactors:blockludicrite>, <bigreactors:blockludicrite>, <bigreactors:blockludicrite>, <bigreactors:oreanglesite>, <avaritia:resource:4>],[<avaritia:resource:4>, <bigreactors:oreanglesite>, <bigreactors:blockludicrite>, <avaritia:resource:6>, <bigreactors:blockludicrite>, <avaritia:resource:6>, <bigreactors:blockludicrite>, <bigreactors:oreanglesite>, <avaritia:resource:4>],[<avaritia:resource:4>, <avaritia:resource:6>, <bigreactors:blockludicrite>, <bigreactors:blockludicrite>, <bigreactors:turbinebearing>, <bigreactors:blockludicrite>, <bigreactors:blockludicrite>, <avaritia:resource:6>, <avaritia:resource:4>],[<avaritia:resource:4>, <bigreactors:oreanglesite>, <bigreactors:blockludicrite>, <avaritia:resource:6>, <bigreactors:blockludicrite>, <avaritia:resource:6>, <bigreactors:blockludicrite>, <bigreactors:oreanglesite>, <avaritia:resource:4>],[<avaritia:resource:4>, <bigreactors:oreanglesite>, <bigreactors:blockludicrite>, <bigreactors:blockludicrite>, <bigreactors:blockludicrite>, <bigreactors:blockludicrite>, <bigreactors:blockludicrite>, <bigreactors:oreanglesite>, <avaritia:resource:4>],[<avaritia:resource:4>, <bigreactors:oreanglesite>, <bigreactors:oreanglesite>, <bigreactors:oreanglesite>, <avaritia:resource:6>, <bigreactors:oreanglesite>, <bigreactors:oreanglesite>, <bigreactors:oreanglesite>, <avaritia:resource:4>],[<singularities:singularity:1>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:4>, <singularities:singularity:1>]]);

//Test remove all avaritia singularity with singularity stuff
recipes.replaceAllOccurences(<avaritia:singularity:3>, <singularities:singularity:3>, <*>);
recipes.replaceAllOccurences(<avaritia:singularity:10>, <singularities:singularity:10>, <*>);
recipes.removeByInput(<avaritia:singularity:3>);
recipes.removeByInput(<avaritia:singularity:10>);

//cheese
recipes.addShaped("sanemake_creativecheese", <rats:creative_cheese>, [
[<rats:block_of_cheese>, <rats:block_of_cheese>, <rats:block_of_cheese>], 
[<rats:block_of_cheese>, <singularities:singularity:76>, <rats:block_of_cheese>],
[<rats:block_of_cheese>, <rats:block_of_cheese>, <rats:block_of_cheese>]]);